### PR TITLE
firebase-list element

### PR DESCRIPTION
**Pull request by mbleigh**
I have to admit, I'm pretty proud of this work. It needs some good hands-on testing but basically I've implemented a `firebase-list` element to handle list-like data. Unlike the naive Array implementation, it works assuming you're using Firebase-generated keys. Best summarized from the addition to the docs below.

Please give me some feedback on this, but I think this is an absolutely vital feature that stumbles most developers new to Polymer/Firebase with its absence.

## firebase-list

Extends `firebase-element` with behaviors for treating a given location as an
ordered list of data.

Lists in Firebase are stored the same as ordinary objects. With `firebase-list`
you can hide much of the complexity of dealing with list-like object data.

Example:

    <firebase-list location="https://YOUR.firebaseio.com/items" data="{{items}}"></firebase-list>

In general `firebase-list` works just like `firebase-element` with a few key
differences:

1. Each item in the `data` array will have `$key` and `$priority` properties that
   relate to their Firebase key and priority. Modifying the `$priority` key will
   set the priority, modifying the `$key` property will delete the data at its
   current location and recreate it at the newly specified key.
2. Instead of observing the properties of the top-level `data` object,
   the properties of each child object are observed. In this way synchronization
   happens across all child items effortlessly.
3. Adding and removing items directly from the `data` array is not supported.
   Instead, you should use the `push` and `remove` methods described below.

When you need to add a new entry to a list, you can use the `push` method with
the data you wish to add as the argument:

    addEntry: function(value) {
      this.$.base.push({foo: value});
    }

To remove a child, simply call the `remove` method with the key of the child
you want to remove as an argument:

    removeEntry: function(item) {
      this.$.base.remove(item.$key);
    }

**Note:** Because you can use this in conjunction with filtering, limiting, and
sorting attributes, it is possible that you may push or remove entries that are
not currently represented in the data.

### CODE REVIEW

**Comment by mbleigh** [comment]
Added ability to properly handle priority and even modifications thereof. Added new demo to exemplify such behavior.

**Comment by mbleigh** [comment]
I originally intended to make this a separate element that extended `firebase-element` -- `firebase-list`. As I implemented it seemed like there were two many "slight modification to the middle of a method" changes for that.

Now that I've implemented the whole thing, I think I see the path to properly implementing it as a separate element. I'd like to hear feedback about which makes more sense.

**Comment by mbleigh** [comment]
OK, made the decision on my own. Here it is in more-or-less final form as an independent element that inherits from `firebase-element`. This is working well in my tests (see `demos` folder) even with complex things like simultaneous changing lots of priorities.

Leaving this here until I get further feedback, but I'd really like to see this land.

**Comment by mbleigh** [comment]
@addyosmani any thoughts?

If you don't think this is a fit for this repo, I'm happy to break it out into its own, but my feeling is that the vast majority of people who would want to use `firebase-element` will have a need for list-handling behavior. And if you *do* want it in this repo but want a different implementation, let me know what you think should be changed.

**Comment by addyosmani** [comment]
Would it be possible to squash your commits? It would greatly help with the review.

**Comment by mbleigh** [comment]
You bet

**Comment by mbleigh** [comment]
Squashed. Changes to `firebase-element` were pretty minimal, only did what was necessary to fix issues that cropped up.

**Comment by kevinpschaaf** [comment]
Hi @mbleigh, awesome work here.  In trying to keep the core set of elements that are supported by the Polymer team maintainable, I think this would be better broken out on its own and registered in one of the web component registries so others can find it.  Thanks for all the hard work and willingness to contribute!

**Comment by mbleigh** [comment]
Hey @kevinpschaaf, respect the sentiment though to me this isn't "bonus" functionality but pretty much table stakes for being able to build real apps with Polymer + Firebase. Can I submit a pull request with the small changes to `firebase-element` that were necessary to get it working and have that accepted? Note that they were all fixes of bugs or shortcomings, not adding functionality just for lists.

**Comment by kevinpschaaf** [comment]
Yes, that would be perfect.

Could you also include info on the need for `job` in `observeQuery`?  That was the only thing I didn't follow after a quick look  Thanks!

**Comment by mbleigh** [comment]
Now available idependently: [divshot/firebase-list](https://github.com/divshot/firebase-list)

**Pull request closed without merging**
